Repository camel-tooling/vscode-camelk, pull requests merged in 2019-08, with the labels that each got.

#57 issue #55 - added additional status bar updates and running/error ind…
  README.md
  images/camelk-integrations-status-bar.jpg
  images/camelk-integrations-view-refresh-action.jpg
  images/camelk-integrations-view-remove-menu.jpg
  images/camelk-integrations-view-settings.jpg
  images/camelk-integrations-view-status-tooltip.jpg
  package.json
  resources/round-k-transparent-16-error.svg
  resources/round-k-transparent-16-running.svg
  src/CamelKNodeProvider.ts
  src/extension.ts
  src/test/integrationExplorer.test.ts
Labels: enhancement

#61 issue #60 - get integration status from json returned by rest call
  src/CamelKNodeProvider.ts
Labels: resolved

#64 issue #53 - adding config-map support - adding secret support - using…
  CHANGELOG.md
  README.md
  images/camelk-integrations-status-bar.jpg
  images/camelk-integrations-view-integrations-log.jpg
  images/camelk-integrations-view-refresh-action.jpg
  images/camelk-integrations-view-remove-menu.jpg
  images/camelk-integrations-view-settings.jpg
  images/camelk-integrations-view-status-tooltip.jpg
  images/camelk-start-integration-dropdown.jpg
  images/kubernetes-configmap-list.jpg
  images/kubernetes-secret-name-command.jpg
  images/kubernetes-view-camelk-hello-xml.jpg
  images/kubernetes-view-camelk-run-xml-menu.jpg
  package-lock.json
  package.json
  src/CamelKNodeProvider.ts
  src/ConfigMapAndSecrets.ts
  src/IntegrationUtils.ts
  src/extension.ts
  src/test/camelkjsonutils.test.ts
  src/test/configmapandsecrets.test.ts
  src/test/extension.test.ts
  src/test/gocamelkkubernetes.test.ts
  src/test/integrationExplorer.test.ts
Labels: enhancement

#73 Update to name approved by Red Hat legal department #72
  CHANGELOG.md
  package.json
Labels: READY FOR REVIEW
