Repository camel-tooling/vscode-camelk, pull requests merged in 2019-09, with the labels that each got.

#83 issue #67 - avoid refreshing integrations view if collapsed
  CHANGELOG.md
  src/CamelKJSONUtils.ts
  src/extension.ts
Labels: READY FOR MERGE

#86 issue #71 and issue #31 - updating development docs
  configure-minikube-camelk.md
  vsc-extension-quickstart.md
Labels: READY FOR MERGE

#96 Prepare for next iteration 0.0.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: PRIO, READY FOR REVIEW

#101 Exclude dependabot branches from non-PR jobs #100
  .travis.yml
Labels: READY FOR REVIEW

#110 Avoid showing output on each message #106
  CHANGELOG.md
  src/CamelKJSONUtils.ts
Labels: PRIO, READY FOR REVIEW

#111 prepare next iteration release 0.0.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: PRIO, READY FOR REVIEW

#107 issue #106 - restructuring integration menu dropdown code
  src/ConfigMapAndSecrets.ts
  src/IntegrationUtils.ts
Labels: PRIO, READY FOR REVIEW

#66 issue #65 - adding extension dependency for k8s extension
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/extension.ts
  src/test/camelkjsonutils.test.ts
  src/test/extension.test.ts
  src/test/integrationExplorer.test.ts
Labels: READY FOR MERGE

#91 issue #56 - adding dev mode option
  CHANGELOG.md
  src/CamelKJSONUtils.ts
  src/IntegrationUtils.ts
Labels: READY FOR MERGE

#85 issue #52 - adding --resource integration capability
  CHANGELOG.md
  src/CamelKNodeProvider.ts
  src/IntegrationUtils.ts
Labels: READY FOR MERGE

#93 issue #51 - adding ability to specify explicit dependencies when depl…
  CHANGELOG.md
  src/IntegrationUtils.ts
Labels: READY FOR REVIEW

#130 issue #58 - adding a listener for server changes to published integra…
  CHANGELOG.md
  src/CamelKNodeProvider.ts
  src/extension.ts
Labels: READY FOR REVIEW

#133 extracting logic from activate into separate functions
  src/extension.ts
Labels: READY FOR REVIEW

#141 another Promise refactoring
  src/CamelKJSONUtils.ts
  src/CamelKNodeProvider.ts
  src/ConfigMapAndSecrets.ts
  src/IntegrationUtils.ts
  src/extension.ts
Labels: READY FOR REVIEW

#140 migrating child process exec to spawn to avoid hanging process
  src/IntegrationUtils.ts
  src/extension.ts
Labels: READY FOR REVIEW
