Repository camel-tooling/vscode-camelk, pull requests merged in 2020-04, with the labels that each got.

#378 FUSETOOLS2-354 - increase timeout for completion test
  src/test/suite/CamelKTaskCompletionItemProvider.test.ts
Labels: PRIO, READY FOR REVIEW

#381 FUSETOOLS2-358 - skip New File test on Jenkins
  src/test/suite/commands/NewIntegrationFileCommand.test.ts
Labels: PRIO, READY FOR REVIEW

#395 Bump vcode-extension-tester version from 2.6.0 to 2.6.2
  package-lock.json
  package.json
Labels: READY FOR REVIEW, dependencies

#396 FUSETOOLS2-411 - rework conditional wait and try to have more details in
  src/test/suite/Utils.ts
  src/test/suite/extension.test.ts
Labels: READY FOR REVIEW
